SIM_HTML = r"""<!doctype html><html><head><meta charset="utf-8"><title>Living Map - Simulation</title><style>
*{box-sizing:border-box}body{margin:0;background:#0a1120;color:#e6edf7;font:13px/1.35 system-ui,sans-serif;height:100vh;display:flex;flex-direction:column}
header{display:flex;align-items:center;gap:14px;padding:7px 14px;background:#0f1a30;border-bottom:1px solid #22314f}header h1{font-size:15px;margin:0}header a{color:#7fb0ff}#ctl{margin-left:auto;display:flex;gap:8px;align-items:center}
button,select{background:#1d5fbf;color:#fff;border:0;padding:6px 12px;border-radius:5px;font-size:12px;cursor:pointer}select{background:#22314f}
#stages{display:flex;gap:6px;padding:8px 14px 2px}.st{flex:1;padding:5px 8px;border-radius:6px;background:#141f38;border:1px solid #22314f;color:#7d8cab;font-size:12px}.st b{display:block;font-size:11px;letter-spacing:.04em}
.st.done{background:#12331f;border-color:#2e7d4a;color:#a6e6bd}.st.cur{background:#3a2c0d;border-color:#ffb43a;color:#ffe0a0;box-shadow:0 0 10px #ffb43a55}
#caption{padding:4px 14px 7px;color:#cdd9ee;min-height:38px}#caption b{color:#ffcf70}
main{flex:1;display:flex;min-height:0}#map{flex:1;position:relative;min-width:0}canvas{width:100%;height:100%;display:block}
#tools{position:absolute;left:10px;top:8px;background:#0f1a30dd;border:1px solid #22314f;border-radius:6px;padding:6px 10px;font-size:12px}#tools label{margin-right:9px;cursor:pointer}
.fb{background:#22314f;margin-right:4px}.fb.on{background:#ffb43a;color:#000}
#tip{position:absolute;pointer-events:none;background:#0f1a30;border:1px solid #4d6ea8;border-radius:6px;padding:6px 9px;max-width:320px;font-size:12px;display:none;z-index:5}
#side{width:430px;background:#0f1a30;border-left:1px solid #22314f;overflow:auto;padding:10px}
.card{background:#16233d;border-radius:8px;padding:9px 10px;margin:0 0 9px}.card h3{margin:0 0 6px;font-size:11px;color:#7fb0ff;text-transform:uppercase;letter-spacing:.06em}
.bar{height:8px;background:#0b1424;border-radius:5px;overflow:hidden;margin:2px 0 5px}.bar i{display:block;height:100%}.vote{display:inline-block;padding:2px 8px;border-radius:10px;margin-right:5px;background:#26314a;color:#7d8cab;font-size:11px}.vote.on{background:#7a2b1a;color:#ffd2c2}
.verdict{margin-top:4px;padding:5px 8px;border-radius:5px;background:#1b2a48}.big{font-size:20px;font-weight:700}.grid2{display:grid;grid-template-columns:1fr 1fr;gap:8px}
.l{padding:4px 6px;border-left:3px solid #445;margin:3px 0;background:#121d35;border-radius:0 4px 4px 0}.l small{color:#8fa0c0}.l .why{display:block;color:#9fb4d8;font-size:11.5px;margin-top:1px}
.WRITER{border-color:#40d0ff}.AMBULANCE{border-color:#7dff9a}.FIRETRUCK{border-color:#ff8a3d}.DRONE{border-color:#d38cff}.GATEWAY{border-color:#ffa640}.UPLINK{border-color:#ffd54d}.STATION{border-color:#c9d6ff}.CMDPOST{border-color:#7fb0ff}.FAULT{border-color:#ff4d4d}.METRICS{border-color:#fff}.MESH{border-color:#b48cff}
.rb{display:flex;gap:8px;align-items:flex-start;margin:4px 0}.dot{display:inline-block;width:11px;height:11px;border-radius:50%;margin-right:5px;vertical-align:middle;flex:none;margin-top:3px}details{color:#b7c6e2}summary{cursor:pointer;color:#7fb0ff}
</style></head><body>
<header><h1 id="ttl">THE LIVING MAP &middot; fire response simulation</h1><span id="hud"></span><a href="/flow" target="_blank">data flow &amp; beacon table &rarr;</a> <a id="cplink" target="_blank">Command Post live map &rarr;</a><div id="ctl"></div></header>
<div id="stages"></div><div id="caption"></div>
<main><div id="map"><canvas id="c"></canvas><div id="tools"><span id="floors"></span>
<label><input type="checkbox" id="t_known" checked> what the Writer knows</label><label><input type="checkbox" id="t_truth" checked> real building</label><label><input type="checkbox" id="t_ghost" checked> other floor (ghost)</label>
<label><input type="checkbox" id="t_links" checked> radio links</label><label><input type="checkbox" id="t_trails" checked> trails</label><label><input type="checkbox" id="t_labels" checked> labels</label></div><div id="tip"></div></div>
<div id="side"><div class="card" id="robots"></div><div class="card" id="sens"></div><div id="met"></div>
<div class="card"><h3>Event log (with plain-language explanations)</h3><div id="log"></div></div>
<div class="card"><details><summary>Legend and glossary</summary><div style="margin-top:6px">
<div><span class="dot" style="background:#40d0ff"></span>Writer &nbsp;<span class="dot" style="background:#7dff9a"></span>Ambulance robot &nbsp;<span class="dot" style="background:#ff8a3d"></span>Fire truck robot &nbsp;<span class="dot" style="background:#d38cff"></span>Drone</div>
<div><span class="dot" style="background:#ff4d4d"></span>P0 critical &nbsp;<span class="dot" style="background:#ffa640"></span>P1 &nbsp;<span class="dot" style="background:#ffe066"></span>P2 &nbsp;<span class="dot" style="background:#8896ab"></span>P3 / relay</div>
<p><b>Van</b>: the Outside Network Area. It carries the antenna, the gateway and all robots. Robots talk only to the van (star network), never to each other.<br><b>Station link</b>: robot &harr; van messages (status, fire out, rescued). Its radio protocol is still to be specified; it is an ideal channel for now.<br><b>Beacon directions</b>: no GPS inside, so every beacon says "I am 4 m ahead, 3 m left of the previous beacon" and "the victim is 2 m ahead of me".<br><b>Stairs / atrium</b>: stairs (S) let ground robots change floor; the atrium shaft (A) is a vertical opening only the drone can use.</p></div></details></div></div></main>
<script>
const C={0:'#ff4d4d',1:'#ffa640',2:'#ffe066',3:'#8896ab'},RC={writer:'#40d0ff',ambulance:'#7dff9a',firetruck:'#ff8a3d',drone:'#d38cff'},RN={writer:'Writer (scout)',ambulance:'Ambulance robot',firetruck:'Fire truck robot',drone:'Fire drone'};
const PR={0:'P0 CRITICAL: relayed immediately',1:'P1 high: next batch or earlier',2:'P2 medium: batch',3:'P3 routine / relay / stairs'};
const STAGES=[
['1 Explore','The <b>Writer</b> enters with <b>no map and no GPS</b>. Its LiDAR builds a private map (blue) on each floor; it climbs stairs to explore upstairs.'],
['2 Detect','A <b>fire needs 2 of 3 sensors to agree</b>. People and animals are seen by the thermal camera. Rubble on the line of sight makes a victim "needs heavy rescue".'],
['3 Drop beacons','Each finding becomes a <b>32-byte beacon</b>: "I am 4 m ahead, 3 m left of the previous one; the victim is 2 m ahead of me; floor 1". Weak radio link? a <b>relay</b> is dropped.'],
['4 Van gateway','The <b>van</b> antenna receives the beacons, checks CRC + signature, rebuilds positions by chaining the hops and converts them to GPS.'],
['5 Command Post','P0 alerts go at once; the rest batch up to 120 s. The Command Post ranks alerts and decides <b>which robot</b> takes which job.'],
['6 Dispatch robots','Robots leave the van with a briefing: <b>ambulance</b> for people, <b>fire truck</b> for ground-floor fires, <b>drone</b> for upper floors. The ambulance waits until fires next to a victim are out.'],
['7 Response','Robots follow the beacon trail, use their own sensors for the last metres, report to the van only, and come back. The Command Post re-dispatches when new targets appear.']];
const EXPL=[[/FIRE beacon/,'Fire confirmed by at least 2 of 3 sensors and written into a beacon.'],[/steam/,'False alarm avoided: only the temperature sensor was high.'],[/REPEATER|link weak/,'Radio margin got thin (walls and floors absorb radio), so a relay was dropped: a denser mesh can heal itself if a beacon dies.'],
[/DEBRIS|human_intervention/,'Rubble blocks the way to a person. Robots cannot lift debris: flagged for the human heavy-rescue team.'],[/HUMAN beacon.*P0/,'Person in immediate danger (fire/gas nearby): priority 0.'],[/HUMAN beacon/,'Person found by the thermal camera.'],[/ANIMAL beacon/,'Animal found (priority 2).'],
[/STAIRS beacon/,'A landmark: this is where robots can change floor (stairs) or where the drone can fly (atrium shaft).'],[/P0_IMMEDIATE/,'Critical alerts bypass the 2-minute buffer and travel with the beacon chain and nearby hazards needed to understand them.'],
[/ADAPTIVE_SCORE/,'A waiting alert became urgent enough (score rose with waiting time) so the batch left early.'],[/BATCH_120S/,'Regular batch: the 120 s bandwidth-saving window ended.'],[/forged/,'Security: a fake packet failed the CRC / signature check.'],
[/DESTROYED/,'Fault: a beacon was destroyed. The mesh re-routes around it and neighbours forward its stored copy.'],[/BEACON_LOST/,'Silence is information: a beacon stopped answering, so a neighbour reported it (likely fire spread or collapse).'],
[/dispatched/,'The Command Post sent this robot out of the van with a briefing.'],[/SKIP/,'Impossible for a robot: needs human heavy equipment.'],[/REACHED/,'The trail brought the robot close; its own sensors finished the approach.'],
[/is OUT/,'Fire extinguished: the robot reports it to the van, which lets the ambulance go in.'],[/drone drop/,'The drone drops extinguishing agent from a hover (limited payload, limited battery).'],[/RESCUED/,'Casualty loaded: the robot returns to the van.'],[/STATION/,'Robot to van message. Robots never talk to each other, only to the van.'],
[/WRITER LOST/,'Writer failed, but everything it found already lives in the beacons and at the Command Post.'],[/exploration complete/,'No unexplored frontier remains.'],[/unreachable/,'The robot could not find a route; the Command Post will not retry the same job forever.'],[/holding/,'The ambulance waits in the van until the fire next to the victim is out.']];
let W=null,S=null,V={s:1,H:1,x0:-8,y0:-13},OBJ=[],built=false,FL=0;
const cv=document.getElementById('c'),g=cv.getContext('2d'),tip=document.getElementById('tip'),$=id=>document.getElementById(id),on=id=>$(id).checked;
function fit(){cv.width=cv.clientWidth*devicePixelRatio;cv.height=cv.clientHeight*devicePixelRatio}addEventListener('resize',fit);fit();
async function ctl(action,value,fault){await fetch('/control',{method:'POST',body:JSON.stringify({action,value,fault})})}
async function init(){W=await (await fetch('/world')).json();poll()}
async function poll(){try{S=await (await fetch('/simstate')).json();if(!built)build();ui();draw()}catch(e){}setTimeout(poll,300)}
function build(){built=true;$('cplink').href=S.cp_url;$('stages').innerHTML=STAGES.map((s,i)=>'<div class="st" id="st'+i+'"><b>'+s[0]+'</b></div>').join('');
 $('ttl').innerHTML='THE LIVING MAP &middot; fire response simulation &middot; '+W.name+(/floor/i.test(W.name)?'':' &middot; '+W.floors.length+' floor'+(W.floors.length>1?'s':''));document.title='The Living Map - '+W.name;
 if(W.floors.length<2){$('t_ghost').parentNode.style.display='none';$('stages').insertAdjacentHTML('afterend','<div style="color:#9fb4d8;font-size:12px;margin:4px 0">This map has one floor: stairs and the second floor are not used and the drone stays docked.</div>')}
 $('floors').innerHTML=W.floors.length<2?'':W.floors.map((f,i)=>'<button class="fb'+(i==0?' on':'')+'" id="fb'+i+'" onclick="setF('+i+')">Floor '+i+'</button>').join('');
 if(S.controls)$('ctl').innerHTML='<button id="pp" onclick="ctl(S.paused?\'resume\':\'pause\')">Pause</button> speed <input type="range" min="1" max="20" step="1" value="'+S.speed+'" oninput="$(\'sv\').textContent=this.value+\'x\'" onchange="ctl(\'speed\',parseFloat(this.value))"><span id="sv">'+S.speed+'x</span> <select id="fs" onchange="ctl(\'restart\',0,this.value)"><option value="none">no fault</option><option value="beacon_destroyed">fault: relay beacon destroyed</option><option value="writer_lost">fault: Writer lost</option></select><button onclick="ctl(\'restart\',0,$(\'fs\').value)">Restart</button>';}
function setF(i){FL=i;W.floors.forEach((f,k)=>$('fb'+k).className='fb'+(k==i?' on':''))}
function explain(m){for(const [re,t] of EXPL)if(re.test(m))return t;return ''}
function ui(){
 const st=S.stages;let cur=st.findIndex(x=>!x);STAGES.forEach((s,i)=>{$('st'+i).className='st '+(st[i]?'done':(i==cur?'cur':''))});
 $('caption').innerHTML=cur<0?'<b>Mission complete.</b> See the results card for times, rescues and fires put out.':'<b>Now: '+STAGES[cur][0].slice(2)+'.</b> '+STAGES[cur][1];
 if(S.controls&&$('pp'))$('pp').textContent=S.paused?'Resume':'Pause';$('hud').innerHTML='sim time <b>'+S.t+' s</b>';
 const fr=S.truth.fires,out=fr.filter(f=>f.I<.1).length,ppl=S.truth.humans.concat(S.truth.animals),res=ppl.filter(p=>p.rescued).length;
 let h='<h3>Robots in the van</h3>';for(const r of ['writer','ambulance','firetruck','drone']){const x=S.robots.find(q=>q.role==r),b=S.board&&S.board[r];
  h+='<div class="rb"><span class="dot" style="background:'+RC[r]+'"></span><div><b>'+RN[r]+'</b>'+(x?' &middot; floor '+x.f:'')+(x&&x.battery!=null?' &middot; battery '+Math.max(0,Math.round(x.battery))+' s':'')+'<br><small>'+(r=='writer'?(x?({dead:'LOST - its memory survives in the beacons',mapped:'building fully mapped',exploring:'exploring with LiDAR only'}[x.state]||x.state):'starting'):(b?b.note:'docked')+(x&&!x.done?' ('+x.state.toLowerCase()+')':''))+'</small></div></div>'}
 h+='<div style="margin-top:6px"><span class="vote on">fires out '+out+'/'+fr.length+'</span><span class="vote on">rescued '+res+'/'+ppl.length+'</span></div>'+((S.awaiting||[]).length?'<button onclick="ctl(\'approve\')">APPROVE DISPATCH</button>':'');$('robots').innerHTML=h;
 const s=S.sensors;if(s){const v3=[s.temp>70,s.thermal>150,s.gas>50],n=v3.filter(x=>x).length;let v='Normal readings.';if(s.temp>70&&n>=2)v='<b style="color:#ff9a7a">FIRE confirmed</b>: '+n+' of 3 sensors agree.';else if(s.temp>70)v='<b style="color:#ffe066">Hot, but only 1 of 3 sensors</b>: probably steam. Rejected.';else if(s.gas>150)v='<b style="color:#c5ff70">Gas leak</b> above threshold.';
  $('sens').innerHTML='<h3>Writer sensors: why "2 of 3"?</h3>Temperature '+s.temp+' &deg;C<div class="bar"><i style="width:'+Math.min(100,s.temp/4.5)+'%;background:#ff7a3d"></i></div>Thermal camera max '+s.thermal+' &deg;C<div class="bar"><i style="width:'+Math.min(100,s.thermal/4.5)+'%;background:#ffb43a"></i></div>Gas '+s.gas+' ppm<div class="bar"><i style="width:'+Math.min(100,s.gas/9)+'%;background:#a7e04a"></i></div><span class="vote '+(v3[0]?'on':'')+'">temp &gt; 70</span><span class="vote '+(v3[1]?'on':'')+'">thermal &gt; 150</span><span class="vote '+(v3[2]?'on':'')+'">gas &gt; 50</span><div class="verdict">'+v+'</div><small>False alarms rejected: '+s.steam+'</small>'}else $('sens').innerHTML='<h3>Writer sensors</h3>waiting...';
 const m=S.metrics;$('met').innerHTML=m?'<div class="card"><h3>Results</h3><div class="grid2"><div>Executor: time to the first person after leaving the van, with beacons<div class="big" style="color:#5dff8a">'+m.with_beacons_s+' s</div></div><div>same Executor searching blind from the entrance<div class="big" style="color:#ff9a7a">'+m.blind_s+' s</div></div><div>search time saved<div class="big">'+(m.gain_pct==null?'-':m.gain_pct+'%')+'</div></div><div>end to end: Writer + briefing + Executor, first person reached<div class=\"big\" style=\"color:#ffd27a\">'+(m.first_person_abs_s==null?'-':m.first_person_abs_s+' s')+'</div></div><div>position error (avg / max)<div class="big">'+(m.position_error_m==null?'n/a in ROS mode':m.position_error_m+' / '+m.position_error_max_m+' m')+'</div></div><div>fires out<div class="big">'+m.fires_out+'/'+m.fires+'</div></div><div>people rescued<div class="big">'+m.rescued+'/'+m.people+'</div></div></div><small>beacons '+m.beacons+' ('+m.repeaters+' relays) &middot; radio delivery '+m.delivery+' &middot; forged packets rejected '+m.rejected+' &middot; needs heavy rescue team: '+((m.skipped||[]).join(', ')||'none')+'</small></div>':'';
 $('log').innerHTML=[...S.log].reverse().slice(0,45).map(l=>{const x=explain(l.msg);return '<div class="l '+l.who+'"><small>'+l.t+' s &middot; '+l.who+'</small> '+l.msg+(x?'<span class="why">&#8627; '+x+'</span>':'')+'</div>'}).join('')}
function draw(){
 if(!W||!S)return;const Wd=cv.width,H=cv.height,x0=-8,x1=42,y0=-13,y1=13,s=Math.min(Wd/(x1-x0),H/(y1-y0));V={s,H,x0,y0};OBJ=[];
 const X=x=>(x-x0)*s,Y=y=>H-(y-y0)*s;g.clearRect(0,0,Wd,H);const c=W.cell;g.font=(11*devicePixelRatio)+'px sans-serif';
 const rows=W.floors[FL],kn=S.known?S.known[FL]:null,gh=W.floors[1-FL>=0&&W.floors.length>1?(FL==0?1:0):0];
 if(on('t_ghost')&&W.floors.length>1){g.fillStyle='rgba(120,140,190,.10)';for(let j=0;j<gh.length;j++)for(let i=0;i<gh[j].length;i++)if(gh[j][i]=='#')g.fillRect(X(W.x0+i*c),Y(W.y0+(j+1)*c),c*s+1,c*s+1)}
 for(let j=0;j<rows.length;j++)for(let i=0;i<rows[j].length;i++){const t=rows[j][i],k=kn?kn[j][i]:'?';let col=null;
  if(t=='#')col=(on('t_known')&&k=='#')?'#7896cf':(on('t_truth')?'#1b2740':null);else if(t=='R')col=(on('t_known')&&k=='R')?'#c08850':(on('t_truth')?'#4a3522':null);
  else if(t=='S')col=(on('t_known')&&k=='S')?'#7fbf5a':(on('t_truth')?'#3a5230':null);else if(t=='A')col=(on('t_known')&&k=='A')?'#6a8fd6':(on('t_truth')?'#233a5c':null);else if(on('t_known')&&k=='.')col='rgba(60,140,255,.15)';
  if(col){g.fillStyle=col;g.fillRect(X(W.x0+i*c),Y(W.y0+(j+1)*c),c*s+1,c*s+1)}}
 W.gas.filter(o=>o.floor==FL).forEach(o=>{const gi=(S.truth.gas||[]).find(q=>q.id==o.id);if(gi&&gi.I<.05){if(on('t_labels')){g.fillStyle='#6a8';g.fillText('gas sealed',X(o.x)-22,Y(o.y))}return}g.fillStyle='rgba(190,255,80,.18)';g.beginPath();g.arc(X(o.x),Y(o.y),3*s,0,7);g.fill();if(on('t_labels')){g.fillStyle='#c5ff70';g.fillText('gas leak',X(o.x)-20,Y(o.y))}OBJ.push({x:o.x,y:o.y,r:2,t:'<b>Leaking gas tank</b><br>explosion risk above 500 ppm'})});
 W.steam.filter(o=>o.floor==FL).forEach(o=>{g.fillStyle='rgba(200,200,220,.3)';g.beginPath();g.arc(X(o.x),Y(o.y),1.2*s,0,7);g.fill();if(on('t_labels')){g.fillStyle='#cfd6e6';g.fillText('steam pipe',X(o.x)-25,Y(o.y)-1.4*s)}OBJ.push({x:o.x,y:o.y,r:1.3,t:'<b>Hot steam pipe</b><br>Raises temperature only: must NOT be reported as fire.'})});
 S.truth.fires.filter(o=>o.f==FL).forEach(o=>{if(o.I<.05){g.fillStyle='#556';g.fillText('out',X(o.x)-8,Y(o.y));return}const R=3.4*s*(.35+.65*o.I),gr=g.createRadialGradient(X(o.x),Y(o.y),2,X(o.x),Y(o.y),R);gr.addColorStop(0,'rgba(255,140,40,.9)');gr.addColorStop(1,'rgba(255,60,0,0)');g.fillStyle=gr;g.beginPath();g.arc(X(o.x),Y(o.y),R,0,7);g.fill();OBJ.push({x:o.x,y:o.y,r:2,t:'<b>Fire '+o.id+'</b><br>intensity '+Math.round(o.I*100)+'%'})});
 const bb={};S.beacons.forEach(b=>bb[b.bid]=b);
 if(on('t_links'))S.beacons.filter(b=>b.f==FL).forEach(b=>{const p=b.parent?bb[b.parent]:null,px=p?p.x:W.van[0],py=p?p.y:W.van[1];g.strokeStyle=b.alive?'rgba(120,170,255,.5)':'rgba(120,120,120,.4)';g.setLineDash([6,5]);g.lineWidth=1.5;g.beginPath();g.moveTo(X(px),Y(py));g.lineTo(X(b.x),Y(b.y));g.stroke();g.setLineDash([])});
 if(on('t_trails'))for(const r in S.trails){const tr=S.trails[r].filter(p=>p[2]==FL);if(tr.length<2)continue;g.strokeStyle=RC[r]+'88';g.lineWidth=2;g.beginPath();tr.forEach((p,i)=>i?g.lineTo(X(p[0]),Y(p[1])):g.moveTo(X(p[0]),Y(p[1])));g.stroke()}
 S.truth.humans.filter(o=>o.f==FL).forEach(o=>{g.fillStyle=o.rescued?'#3aa55a':'#ff6b6b';g.beginPath();g.arc(X(o.x),Y(o.y),8,0,7);g.fill();g.fillStyle='#fff';g.fillText(o.rescued?'\u2713':'H',X(o.x)-4,Y(o.y)+4);OBJ.push({x:o.x,y:o.y,r:1,t:'<b>Person '+o.id+'</b> (ground truth)'+(o.rescued?'<br>rescued':'')})});
 S.truth.animals.filter(o=>o.f==FL).forEach(o=>{g.fillStyle=o.rescued?'#3aa55a':'#ffe066';g.beginPath();g.arc(X(o.x),Y(o.y),7,0,7);g.fill();g.fillStyle='#000';g.fillText(o.rescued?'\u2713':'A',X(o.x)-4,Y(o.y)+4);OBJ.push({x:o.x,y:o.y,r:1,t:'<b>Animal '+o.id+'</b>'+(o.rescued?' rescued':'')})});
 if(FL==0){{const vl=Math.max(14,(W.van_size?W.van_size[0]:2.6)*s),vw=Math.max(9,(W.van_size?W.van_size[1]:1.3)*s);g.fillStyle='#4da3ff';g.fillRect(X(W.van[0])-vl/2,Y(W.van[1])-vw/2,vl,vw);g.fillStyle='#fff';g.fillText('VAN',X(W.van[0])-11,Y(W.van[1])+4)}OBJ.push({x:W.van[0],y:W.van[1],r:2,t:'<b>Van (Outside Network Area)</b><br>antenna + gateway + all robots. The only station: robots talk to the van, never to each other.'})}
 S.beacons.filter(b=>b.f==FL).forEach(b=>{g.strokeStyle=b.alive?C[b.prio]:'#666';g.lineWidth=2.5;g.beginPath();g.arc(X(b.x),Y(b.y),b.type=='REPEATER'?4:6,0,7);g.stroke();if(!b.alive){g.beginPath();g.moveTo(X(b.x)-6,Y(b.y)-6);g.lineTo(X(b.x)+6,Y(b.y)+6);g.moveTo(X(b.x)+6,Y(b.y)-6);g.lineTo(X(b.x)-6,Y(b.y)+6);g.stroke()}
  if(on('t_labels')&&b.type!='REPEATER'){g.fillStyle='#dce8fb';g.fillText(b.type+' #'+b.bid,X(b.x)+9,Y(b.y)-7)}
  const ins=S.instr&&S.instr[b.bid];OBJ.push({x:b.x,y:b.y,r:.7,t:'<b>Beacon #'+b.bid+' &middot; '+b.type+'</b><br>'+PR[b.prio]+(ins?'<br>I am '+ins[0]+'<br>target: '+ins[1]:'')+(b.alive?'':'<br><b style="color:#ff7a7a">destroyed</b>')})});
 g.lineWidth=1;S.robots.filter(r=>r.f==FL).forEach(r=>{const col=RC[r.role];g.fillStyle=col;g.beginPath();if(r.role=='drone'){g.moveTo(X(r.x),Y(r.y)-11);g.lineTo(X(r.x)+10,Y(r.y)+8);g.lineTo(X(r.x)-10,Y(r.y)+8);g.closePath()}else g.arc(X(r.x),Y(r.y),9,0,7);g.fill();g.fillStyle='#000';g.fillText({writer:'W',ambulance:'A',firetruck:'F',drone:'D'}[r.role],X(r.x)-4,Y(r.y)+(r.role=='drone'?6:4));
  OBJ.push({x:r.x,y:r.y,r:1,t:'<b>'+RN[r.role]+'</b><br>'+r.state.toLowerCase()+(r.battery!=null?'<br>battery '+Math.round(r.battery)+' s':'')})});
 g.fillStyle='#9fb4d8';g.fillText('FLOOR '+FL+(W.floors.length>1?'   (use the buttons to switch)':''),X(-7.5),Y(12))}
cv.addEventListener('mousemove',ev=>{const r=cv.getBoundingClientRect(),px=(ev.clientX-r.left)*devicePixelRatio,py=(ev.clientY-r.top)*devicePixelRatio;const wx=px/V.s+V.x0,wy=(V.H-py)/V.s+V.y0;let best=null,bd=1e9;
 for(const o of OBJ){const d=Math.hypot(o.x-wx,o.y-wy);if(d<o.r+.3&&d<bd){bd=d;best=o}}
 if(best){tip.style.display='block';tip.style.left=(ev.clientX-r.left+14)+'px';tip.style.top=(ev.clientY-r.top+14)+'px';tip.innerHTML=best.t}else tip.style.display='none'});
cv.addEventListener('mouseleave',()=>tip.style.display='none');init();
</script></body></html>"""
